### ISSUE TITLE
cors does not work

### ISSUE THREAD

**Issue by hubingkang** [cg-dot/vertexai-cf-workers#5]
<img width="775" alt="image" src="https://github.com/user-attachments/assets/f1503f6f-7709-4c72-b5ea-9d2865aebef2">

**Comment by cg-dot** [comment]
It should be fixed in the latest commit. Have you tried updating to the latest commit?

**Comment by hubingkang** [comment]
> t should be fixed in the latest commit. Have you tried updating to the latest commit?

yes, I use the latest commit

**Comment by cg-dot** [comment]
> yes, I use the latest commit

Can you share more details? (response headers etc.)
