### ISSUE TITLE
Follow the instructions step by step and the prompts are as follows.

### ISSUE THREAD

**Issue by billowssun** [cg-dot/vertexai-cf-workers#8]
![image](https://github.com/user-attachments/assets/eec47962-f9fd-4a14-84a6-6e9d601f4907)

**Comment by EWING-ZHANG** [comment]
I got the same problem.

**Comment by cg-dot** [comment]
You should use the POST method. (You can refer to the documentation here: https://docs.anthropic.com/en/api/messages)

**Comment by billowssun** [comment]
> You should use the POST method. (You can refer to the documentation here: https://docs.anthropic.com/en/api/messages)

On top of your tutorial, what exactly should I do?

**Comment by cg-dot** [comment]
> On top of your tutorial, what exactly should I do?

Once you have the necessary values and have set the workers variable, you can call it in the same way as the Anthropic API.

**Comment by billowssun** [comment]
![image](https://github.com/user-attachments/assets/46ad00b4-0369-42cd-9ec7-0e530b026cbf)
Where did the error occur, please?

**Comment by billowssun** [comment]
![image](https://github.com/user-attachments/assets/01bbe41a-7b63-4e1a-ab2d-5d82c7b8fe3c)
![image](https://github.com/user-attachments/assets/7c94f969-31eb-4461-a816-4f34a3f59161)
Please help me!!!

**Comment by EWING-ZHANG** [comment]
我是直接把环境变量在js里面写死的，你这个header里面需要加一个x-api-key,值需要和js里面写的api_key相等

**Comment by billowssun** [comment]
> 我是直接把环境变量在js里面写死的，你这个header里面需要加一个x-api-key,值需要和js里面写的api_key相等

![image](https://github.com/user-attachments/assets/a81fdb3b-55d5-47f7-8478-248a4701f079)
改进过后，错误代码又变成400了，这是账号问题吗

**Comment by EWING-ZHANG** [comment]
{
    "model": "claude-3-5-sonnet",
    "max_tokens": 4096,
    "messages": [
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "chatgpt中的token是什么意思"
                }
            ]
        }
    ]
}


你可以参考我这个body，text的内容换成你需要问的东西就行

**Comment by billowssun** [comment]
> { "model": "claude-3-5-sonnet", "max_tokens": 4096, "messages": [ { "role": "user", "content": [ { "type": "text", "text": "chatgpt中的token是什么意思" } ] } ] }
> 
> 你可以参考我这个body，text的内容换成你需要问的东西就行

![image](https://github.com/user-attachments/assets/f07de75f-12a0-4c5e-b47e-55040a738913)
还是不行大佬！

**Comment by billowssun** [comment]
解决了，是CGP没有成功启用Claude模型。

**Comment by Nicecsh** [comment]
> 解决了，是CGP没有成功启用Claude模型。
请问大佬，我添加了x-api-key后，怎么还是出现错误提示？
{"type":"error","error":{"type":"authentication_error","message":"invalid x-api-key"}}

![Uploading 111.png…]()
